import {initializeApp} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";import {getFirestore,doc,getDoc,setDoc,updateDoc,collection,onSnapshot,addDoc,deleteDoc,query,orderBy} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";import {getStorage,ref,uploadBytes,getDownloadURL,listAll} from "https://www.gstatic.com/firebasejs/11.0.2/firebase-storage.js";import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);let content={},products=[],articles=[];
const $=id=>document.getElementById(id);function showTab(n){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));$("tab-"+n).classList.add("active")}document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$("loginForm").onsubmit=async e=>{e.preventDefault();let user=$("username").value.trim().toLowerCase(),pass=$("password").value;let email=user.includes("@")?user:"admin@kitchenzen.local";try{$("loginMsg").textContent="Logging in...";await signInWithEmailAndPassword(auth,email,pass)}catch(err){$("loginMsg").textContent=err.message}};
$("logout").onclick=()=>signOut(auth);onAuthStateChanged(auth,async u=>{if(!u){$("loginView").hidden=false;$("adminView").hidden=true;return}let a=await getDoc(doc(db,"admins",u.uid));if(!a.exists()){await signOut(auth);$("loginMsg").textContent="This account is not an admin.";return}$("loginView").hidden=true;$("adminView").hidden=false;start()});
function start(){onSnapshot(doc(db,"siteContent","main"),s=>{content=s.data()||{};fillContent()});onSnapshot(collection(db,"products"),s=>{products=s.docs.map(x=>({id:x.id,...x.data()}));$("productCount").textContent=products.length;renderProducts()});onSnapshot(collection(db,"articles"),s=>{articles=s.docs.map(x=>({id:x.id,...x.data()}));$("articleCount").textContent=articles.length;renderArticles()});loadGallery()}
function fillContent(){$("heroTitleInput").value=content.heroTitle||"";$("heroSubtitleInput").value=content.heroSubtitle||"";$("heroImageInput").value=content.heroImage||"";$("aboutTitleInput").value=content.aboutTitle||"";$("aboutTextInput").value=content.aboutText||"";$("contactEmailInput").value=content.contactEmail||"";$("facebookInput").value=content.social?.facebook||"";$("instagramInput").value=content.social?.instagram||"";$("youtubeInput").value=content.social?.youtube||"";$("profilePhotoInput").value=content.profilePhoto||"";$("fontSelect").value=content.font||"modern"}
$("homeForm").onsubmit=async e=>{e.preventDefault();await updateDoc(doc(db,"siteContent","main"),{heroTitle:$("heroTitleInput").value,heroSubtitle:$("heroSubtitleInput").value,heroImage:$("heroImageInput").value});alert("Saved. Live website updated.")};
$("aboutForm").onsubmit=async e=>{e.preventDefault();await updateDoc(doc(db,"siteContent","main"),{aboutTitle:$("aboutTitleInput").value,aboutText:$("aboutTextInput").value,contactEmail:$("contactEmailInput").value,profilePhoto:$("profilePhotoInput").value,social:{facebook:$("facebookInput").value,instagram:$("instagramInput").value,youtube:$("youtubeInput").value}});alert("Saved.")};
document.querySelectorAll("[data-theme]").forEach(b=>b.onclick=()=>{content._theme=b.dataset.theme;document.querySelectorAll("[data-theme]").forEach(x=>x.style.outline="");b.style.outline="3px solid #c86d40"});$("saveAppearance").onclick=async()=>{await updateDoc(doc(db,"siteContent","main"),{theme:content._theme||content.theme||"sage",font:$("fontSelect").value});alert("Theme saved and live website updated.")};
function productForm(p={active:true}){return `<h3>${p.id?"Edit":"Add"} Product</h3><label>Name<input id="pname" value="${p.name||""}"></label><label>Description<textarea id="pdesc">${p.description||""}</textarea></label><label>Price<input id="pprice" value="${p.price||""}"></label><label>Rating<input id="prating" value="${p.rating||"4.8"}"></label><label>Category<input id="pcat" value="${p.category||""}"></label><label>Image URL<input id="pimage" value="${p.image||""}"></label><label>Buy Button URL<input id="purl" value="${p.url||""}"></label><label><input id="pactive" type="checkbox" ${p.active!==false?"checked":""}> Show on website</label><button id="saveProduct">Save Product</button>`}
$("newProduct").onclick=()=>{$("productEditor").hidden=false;$("productEditor").innerHTML=productForm();bindProduct(null)};
function bindProduct(id){$("saveProduct").onclick=async()=>{let d={name:$("pname").value,description:$("pdesc").value,price:$("pprice").value,rating:$("prating").value,category:$("pcat").value,image:$("pimage").value,url:$("purl").value,active:$("pactive").checked};id?await setDoc(doc(db,"products",id),d):await addDoc(collection(db,"products"),d);$("productEditor").hidden=true}}
function renderProducts(){$("productList").innerHTML=products.map(p=>`<div class="list-item"><img src="${p.image||""}"><div class="info"><h3>${p.name}</h3><p>${p.price||""} • ${p.category||""}</p></div><button onclick="editProduct('${p.id}')">Edit</button><button class="danger" onclick="removeProduct('${p.id}')">Delete</button></div>`).join("")}
window.editProduct=id=>{let p=products.find(x=>x.id===id);$("productEditor").hidden=false;$("productEditor").innerHTML=productForm(p);bindProduct(id)};window.removeProduct=async id=>{if(confirm("Delete this product?"))await deleteDoc(doc(db,"products",id))}
function articleForm(a={active:true}){return `<h3>${a.id?"Edit":"Add"} Article</h3><label>Title<input id="atitle" value="${a.title||""}"></label><label>Excerpt<textarea id="aexcerpt">${a.excerpt||""}</textarea></label><label>Full Article<textarea id="acontent">${a.content||""}</textarea></label><label>Image URL<input id="aimage" value="${a.image||""}"></label><label><input id="aactive" type="checkbox" ${a.active!==false?"checked":""}> Show on website</label><button id="saveArticle">Save Article</button>`}
$("newArticle").onclick=()=>{$("articleEditor").hidden=false;$("articleEditor").innerHTML=articleForm();bindArticle(null)};function bindArticle(id){$("saveArticle").onclick=async()=>{let d={title:$("atitle").value,excerpt:$("aexcerpt").value,content:$("acontent").value,image:$("aimage").value,active:$("aactive").checked};id?await setDoc(doc(db,"articles",id),d):await addDoc(collection(db,"articles"),d);$("articleEditor").hidden=true}}
function renderArticles(){$("articleList").innerHTML=articles.map(a=>`<div class="list-item"><img src="${a.image||""}"><div class="info"><h3>${a.title}</h3><p>${a.excerpt||""}</p></div><button onclick="editArticle('${a.id}')">Edit</button><button class="danger" onclick="removeArticle('${a.id}')">Delete</button></div>`).join("")}
window.editArticle=id=>{let a=articles.find(x=>x.id===id);$("articleEditor").hidden=false;$("articleEditor").innerHTML=articleForm(a);bindArticle(id)};window.removeArticle=async id=>{if(confirm("Delete this article?"))await deleteDoc(doc(db,"articles",id))}
$("uploadImage").onclick=async()=>{let f=$("imageFile").files[0];if(!f)return;$("uploadMsg").textContent="Uploading...";let r=ref(storage,"images/"+Date.now()+"-"+f.name);await uploadBytes(r,f);let u=await getDownloadURL(r);$("uploadMsg").innerHTML=`Uploaded! Copy this URL: <input value="${u}">`;loadGallery()};
async function loadGallery(){try{let r=await listAll(ref(storage,"images"));let urls=await Promise.all(r.items.map(i=>getDownloadURL(i)));$("imageCount").textContent=urls.length;$("imageGallery").innerHTML=urls.map(u=>`<img src="${u}">`).join("")}catch(e){}}
