import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import { getFirestore, doc, onSnapshot, collection, query, where, orderBy, getDocs } from "https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig), db=getFirestore(app);
const defaults={heroTitle:"Upgrade Your Kitchen.\nElevate Your Life.",heroSubtitle:"Helpful buying guides, practical product reviews, and kitchen ideas designed to make everyday decisions easier.",heroImage:"https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1200&q=80",aboutTitle:"Making kitchen research easier.",aboutText:"KitchenZen is a modern editorial-style kitchen website focused on useful buying guides, product comparisons and practical recommendations.",contactEmail:"hello@kitchenzen.com",theme:"sage",font:"modern",categories:[["♨","Air Fryers"],["♜","Blenders"],["⚔","Knives"],["▱","Cookware"],["☕","Coffee Makers"],["▣","Toasters"],["◉","Food Processors"],["✦","Kitchen Gadgets"]],social:{}};
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function apply(data){const d={...defaults,...data};document.body.dataset.theme=d.theme;document.body.dataset.font=d.font;document.getElementById("heroTitle").innerHTML=esc(d.heroTitle).replace(/\n/g,"<br>");document.getElementById("heroSubtitle").textContent=d.heroSubtitle;document.getElementById("heroImage").src=d.heroImage;document.getElementById("aboutTitle").textContent=d.aboutTitle;document.getElementById("aboutText").textContent=d.aboutText;const email=document.getElementById("contactEmail");email.textContent=d.contactEmail;email.href="mailto:"+d.contactEmail;document.getElementById("categoriesGrid").innerHTML=d.categories.map(c=>`<div class="category"><div class="category-icon">${c[0]}</div><strong>${esc(c[1])}</strong></div>`).join("");document.getElementById("socialLinks").innerHTML=Object.entries(d.social||{}).filter(([,v])=>v).map(([k,v])=>`<a href="${esc(v)}" target="_blank" rel="noopener">${esc(k)}</a>`).join("");}
onSnapshot(doc(db,"siteContent","main"),s=>apply(s.exists()?s.data():defaults));
onSnapshot(query(collection(db,"products"),where("active","==",true)),s=>{document.getElementById("productsGrid").innerHTML=s.docs.map(x=>{let p=x.data();return `<article class="product-card"><div class="product-image"><img src="${esc(p.image||'')}" alt="${esc(p.name)}"></div><div class="product-body"><div class="rating">★★★★★ ${esc(p.rating||'')}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="price">${esc(p.price||'')}</div><br><a class="button primary" href="${esc(p.url)}" target="_blank" rel="nofollow sponsored noopener">Buy Now</a></div></article>`}).join("")});
let articles=[];onSnapshot(query(collection(db,"articles"),where("active","==",true)),s=>{articles=s.docs.map(x=>({id:x.id,...x.data()}));document.getElementById("guidesGrid").innerHTML=articles.map((a,i)=>`<article class="guide-card"><div class="guide-image"><img src="${esc(a.image||'')}" alt="${esc(a.title)}"></div><div class="guide-body"><h3>${esc(a.title)}</h3><p>${esc(a.excerpt)}</p><button class="read-button" data-i="${i}">Read Article →</button></div></article>`).join("");document.querySelectorAll(".read-button").forEach(b=>b.onclick=()=>openArticle(articles[+b.dataset.i]));});
function openArticle(a){document.getElementById("modalContent").innerHTML=`<p class="eyebrow">KITCHENZEN GUIDE</p><h2>${esc(a.title)}</h2><div class="article-content">${esc(a.content||a.excerpt||"")}</div>`;document.getElementById("articleModal").classList.add("show")}
document.getElementById("closeModal").onclick=()=>document.getElementById("articleModal").classList.remove("show");document.getElementById("menuButton").onclick=()=>document.getElementById("navigation").classList.toggle("open");